nelmio_cors:
    defaults:
        allow_origin: ['*']
        origin_regex: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
                allow_origin: ['*']
                origin_regex: true
                allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
                allow_headers: ['Content-Type', 'Authorization']
                expose_headers: ['Link']
                max_age: 3600
        '^/api/v1':
                allow_origin: ['*']
                origin_regex: true
                allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
                allow_headers: ['Content-Type', 'Authorization']
                expose_headers: ['Link']
                max_age: 3600

