# Generated by Django 4.0.4 on 2022-06-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
