# Generated by Django 4.0.4 on 2022-06-17 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_django', '0002_alter_sneakermodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakermodel',
            name='release_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
