<?php

namespace ContainerXeo1Dwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_TransportFactory_MailgunService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailer.transport_factory.mailgun' shared service.
     *
     * @return \Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailgun-mailer/Transport/MailgunTransportFactory.php';

        return new \Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), NULL, ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
    }
}
