<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSJrpo3O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSJrpo3O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSJrpo3O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSJrpo3O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSJrpo3O\App_KernelDevDebugContainer([
    'container.build_hash' => 'SJrpo3O',
    'container.build_id' => '6bf1e66a',
    'container.build_time' => 1655389349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSJrpo3O');
